/**
 * Deterministic emitter for the generated data/ tree.
 * Fixed key order and fixed rounding so refreshes produce clean git diffs.
 * Writes to a temp dir first, then swaps, so a failed run never leaves
 * half-written committed data.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { ChartFile, CorrelationFile, Meta, Rankings } from '../shared/types.ts';

export interface Snapshot {
  meta: Meta;
  rankings: Rankings;
  correlation: CorrelationFile;
  charts: { fileKey: string; file: ChartFile }[];
}

export const round = (v: number, dp: number): number => {
  const f = 10 ** dp;
  return Math.round(v * f) / f;
};

const DATA_DIR = path.join(import.meta.dirname, '..', 'data');

export function writeSnapshot(snapshot: Snapshot): void {
  const tmp = path.join(DATA_DIR, '.tmp-write');
  fs.rmSync(tmp, { recursive: true, force: true });
  fs.mkdirSync(path.join(tmp, 'charts'), { recursive: true });

  fs.writeFileSync(path.join(tmp, 'meta.json'), JSON.stringify(snapshot.meta, null, 2) + '\n');
  fs.writeFileSync(path.join(tmp, 'rankings.json'), JSON.stringify(snapshot.rankings) + '\n');
  fs.writeFileSync(path.join(tmp, 'correlation.json'), JSON.stringify(snapshot.correlation) + '\n');

  const sortedCharts = [...snapshot.charts].sort((a, b) => a.fileKey.localeCompare(b.fileKey));
  for (const { fileKey, file } of sortedCharts) {
    if (!/^[A-Z0-9.-]+$/i.test(fileKey)) throw new Error(`unsafe chart file key: ${fileKey}`);
    fs.writeFileSync(path.join(tmp, 'charts', `${fileKey}.json`), JSON.stringify(file) + '\n');
  }

  const indexLines = [
    '// AUTO-GENERATED by scripts/write.ts — do not edit.',
    '// Lazy require thunks: Metro bundles every chart, but each JSON is parsed',
    '// only when a ticker is first opened.',
    "import type { ChartFile } from '../../shared/types';",
    '',
    'export const chartFiles: Record<string, () => ChartFile> = {',
    ...sortedCharts.map(
      ({ fileKey }) => `  '${fileKey}': () => require('./${fileKey}.json') as ChartFile,`,
    ),
    '};',
    '',
  ];
  fs.writeFileSync(path.join(tmp, 'charts', 'index.ts'), indexLines.join('\n'));

  // Swap into place.
  for (const name of ['meta.json', 'rankings.json', 'correlation.json']) {
    fs.renameSync(path.join(tmp, name), path.join(DATA_DIR, name));
  }
  fs.rmSync(path.join(DATA_DIR, 'charts'), { recursive: true, force: true });
  fs.renameSync(path.join(tmp, 'charts'), path.join(DATA_DIR, 'charts'));
  fs.rmSync(tmp, { recursive: true, force: true });
}
